import java.sql.Date;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.*;

public class ContratarPlan extends javax.swing.JFrame {
    
    private SentenciasSQL sql;
    private LocalDate fecha = LocalDate.now();

    public ContratarPlan(SentenciasSQL sql) {
        this.sql = sql;
        initComponents();
        cmbIdPlanes.setVisible(false);
        cmbRuts.setVisible(false);
        llenarCombos();
        llenarAlumnos();
    }
    public ContratarPlan(){}
   
    public void llenarCombos(){
        for (String plan : sql.getListaPlanes()){
            cmbPlanes.addItem(plan);
        }
        
        for (String id : sql.getListaIdPlanes()){
            cmbIdPlanes.addItem(id);
        }
    }
    public void llenarAlumnos(){
        for (String alumno : sql.getAlumnos()) {
            cmbAlumnos.addItem(alumno);
        }
        
        
        for (String rut : sql.getRutAlumnos()){
            cmbRuts.addItem(rut);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmdConfirmarPlan = new javax.swing.JButton();
        cmdSalir = new javax.swing.JButton();
        lblElegirPlan = new javax.swing.JLabel();
        cmbPlanes = new javax.swing.JComboBox<>();
        cmbIdPlanes = new javax.swing.JComboBox<>();
        cmbRuts = new javax.swing.JComboBox<>();
        cmbAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 600));

        jPanel1.setBackground(new java.awt.Color(186, 186, 186));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/durga.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 10, 143, 200);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Contratar nuevo plan");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(241, 6, 181, 25);

        cmdConfirmarPlan.setText("Confirmar");
        cmdConfirmarPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdConfirmarPlanActionPerformed(evt);
            }
        });
        jPanel1.add(cmdConfirmarPlan);
        cmdConfirmarPlan.setBounds(50, 300, 84, 23);

        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSalir);
        cmdSalir.setBounds(460, 300, 72, 23);

        lblElegirPlan.setText("Elija el plan que desea contratar: ");
        jPanel1.add(lblElegirPlan);
        lblElegirPlan.setBounds(160, 100, 172, 16);

        jPanel1.add(cmbPlanes);
        cmbPlanes.setBounds(340, 100, 149, 22);

        cmbIdPlanes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbIdPlanesActionPerformed(evt);
            }
        });
        jPanel1.add(cmbIdPlanes);
        cmbIdPlanes.setBounds(170, 160, 72, 22);

        jPanel1.add(cmbRuts);
        cmbRuts.setBounds(280, 160, 72, 22);

        jPanel1.add(cmbAlumnos);
        cmbAlumnos.setBounds(270, 60, 220, 22);

        jLabel3.setText("Elija al alumno:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 60, 110, 16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_cmdSalirActionPerformed
    
    private void cmbIdPlanesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbIdPlanesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbIdPlanesActionPerformed

    private void cmdConfirmarPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdConfirmarPlanActionPerformed
        String rut = cmbRuts.getItemAt(cmbAlumnos.getSelectedIndex());
        int id = Integer.parseInt(cmbIdPlanes.getItemAt(cmbPlanes.getSelectedIndex()));
        ContratoPlan c = new ContratoPlan(rut,id,Date.valueOf(fecha),Date.valueOf(fecha.plusDays(31)),sql.getNumClases(id));
        sql.guardar(c.getInsert());

    }//GEN-LAST:event_cmdConfirmarPlanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContratarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContratarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContratarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContratarPlan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ContratarPlan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbAlumnos;
    private javax.swing.JComboBox<String> cmbIdPlanes;
    private javax.swing.JComboBox<String> cmbPlanes;
    private javax.swing.JComboBox<String> cmbRuts;
    private javax.swing.JButton cmdConfirmarPlan;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblElegirPlan;
    // End of variables declaration//GEN-END:variables
}
