/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author valen
 */
public class Interfaz extends javax.swing.JFrame {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmdAsistencia = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmdAgregar = new javax.swing.JButton();
        cmdContratar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cmdSalir = new javax.swing.JButton();
        cmdCerrarDia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(186, 186, 186));
        jPanel1.setLayout(null);

        cmdAsistencia.setText("Tomar asistencia");
        cmdAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAsistenciaActionPerformed(evt);
            }
        });
        jPanel1.add(cmdAsistencia);
        cmdAsistencia.setBounds(40, 340, 130, 23);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Control de Asistencia \"Espacio Durga\"");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 20, 440, 30);

        cmdAgregar.setText("Agregar nuevo alumno");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdAgregar);
        cmdAgregar.setBounds(210, 340, 160, 23);

        cmdContratar.setText("Contratar plan");
        cmdContratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdContratarActionPerformed(evt);
            }
        });
        jPanel1.add(cmdContratar);
        cmdContratar.setBounds(410, 340, 120, 23);

        jLabel2.setText("Bienvenido al menu, a continuacion elija una opcion:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(150, 300, 290, 16);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(370, 260, 0, 3);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/durga.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 50, 150, 230);

        cmdSalir.setText("Salir");
        cmdSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSalirActionPerformed(evt);
            }
        });
        jPanel1.add(cmdSalir);
        cmdSalir.setBounds(430, 400, 75, 23);

        cmdCerrarDia.setText("Cerrar dia");
        jPanel1.add(cmdCerrarDia);
        cmdCerrarDia.setBounds(70, 400, 100, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 580, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAsistenciaActionPerformed
        TomarAsistencia T_asis = new TomarAsistencia();
        T_asis.setVisible(true);
                
               
    }//GEN-LAST:event_cmdAsistenciaActionPerformed

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
        NuevoAlumno N_alum = new NuevoAlumno();
        N_alum.setVisible(true);
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void cmdSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_cmdSalirActionPerformed

    private void cmdContratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdContratarActionPerformed
        ContratarPlan C_plan = new ContratarPlan();
        C_plan.setVisible(true);
    }//GEN-LAST:event_cmdContratarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interfaz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Interfaz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdAsistencia;
    private javax.swing.JButton cmdCerrarDia;
    private javax.swing.JButton cmdContratar;
    private javax.swing.JButton cmdSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
